Desktop/doctors-office-main/Office/Models/Patient.cs
using System.Collections.Generic;

namespace Office.Models
{
  public class Patient
  {
    public Patient()
    {
      // this.Doctors = new HashSet<DoctorPatient>();
      this.Specialties = new HashSet<DoctorPatientSpecialty>();
      this.Doctors = new HashSet<DoctorPatientSpecialty>();
    }

    public int PatientId { get; set; }
    public string PatientName { get; set; }
    public string DOB { get; set; }

    public ICollection<DoctorPatientSpecialty> Doctors { get; }
    public ICollection<DoctorPatientSpecialty> Specialties { get; }
  }
}

Desktop/doctors-office-main/Office/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Mvc;
using Office.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Office.Controllers
{
  public class PatientsController : Controller
  {
    private readonly OfficeContext _db;
  
    public PatientsController(OfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Patients.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "DoctorName", "DoctorSpecialty");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
      if (DoctorId != 0)
      {
        _db.DoctorPatientSpecialties.Add(new DoctorPatientSpecialty(){
          DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
        .Include(patient => patient.Doctors)
        .ThenInclude(join => join.Doctor)
        .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    public ActionResult Edit(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "DoctorName");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatientSpecialties.Add(new DoctorPatientSpecialty(){
          DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.Entry(patient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDoctor(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "DoctorName");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatientSpecialties.Add(new DoctorPatientSpecialty() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      _db.Patients.Remove(thisPatient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDoctor(int joinId)
    {
      var joinEntry = _db.DoctorPatientSpecialties.FirstOrDefault(entry => entry.DoctorPatientSpecialtyId == joinId);
      _db.DoctorPatientSpecialties.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Desktop/doctors-office-main/Office/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Patient

<h2>Add a Doctor</h2>

<h2>Add a Doctor for: @Html.DisplayFor(model => model.PatientName)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PatientId)

    @Html.Label("Select Doctor")
    @Html.DropDownList("DoctorId")

    <input type="submit" value="Save" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to Patients", "Index")</p>

Desktop/doctors-office-main/Office/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Patient

<h4>Enroll a new Patient</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.PatientName)
    @Html.TextBoxFor(model => model.PatientName)

    @Html.Label("Select Doctor")
    @Html.DropDownList("DoctorId")

    @Html.Label("Date of Birth")
    @Html.TextBoxFor(model => model.DOB, new { @type = "date"})

    <input type="submit" value="Enroll new Patient" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Patients", "Index")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

Desktop/doctors-office-main/Office/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Patient

<h2>Are you sure you want to delete this Patient?</h2>

@Html.DisplayNameFor(model => model.PatientName): @Html.DisplayFor(model => model.PatientName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-default"/>
}

@Html.ActionLink("Back To Patients", "Index")

Desktop/doctors-office-main/Office/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Patient

<h2>Patient Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.PatientName): @Html.DisplayFor(model => model.PatientName)</h3>
<h3>@Html.DisplayNameFor(model => model.DOB): @Html.DisplayFor(model => model.DOB)</h3>
  @if(@Model.Doctors.Count == 0)
  {
  <p>This Patient is not enrolled for any Doctors</p>
  }
  else
  {
    <h4>Doctors the Patient is enrolled in:</h4>
    <ul>
    @foreach(var join in Model.Doctors)
    {
      <li>@join.Doctor.DoctorName</li>
    }
    </ul>
  }

  <ul>
  @foreach(var join in Model.Doctors)
  {
    <li>@join.Doctor.DoctorName</li>
    @using (Html.BeginForm("DeleteDoctor", "Patients"))
    {
      @Html.Hidden("joinId", @join.DoctorPatientSpecialtyId)
      <input type="submit" value="Delete" class="btn btn-default"/>
    } 
  }
  </ul>

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Patient", "Edit", new { id = Model.PatientId})</p>
<p>@Html.ActionLink("Delete Patient", "Delete", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Add a Doctor", "AddDoctor", new { id = Model.PatientId })</p>

Desktop/doctors-office-main/Office/Views/Patients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Patient

<h2>Edit</h2>

<h4>Edit: @Html.DisplayFor(model => model.PatientName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  @Html.LabelFor(model => model.PatientName)
  @Html.EditorFor(model => model.PatientName)

  @Html.Label("Select a Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Save" class="btn btn-default" />
  
}

<p>@Html.ActionLink("Back to Patients", "Index")</p>

Desktop/doctors-office-main/Office/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using Office.Models;
@model List<Office.Models.Patient>;

<h1>Enrolled Patients:</h1>

@if (@Model.Count == 0)
{
  <h2>No Patients have been enrolled yet...</h2>
}

@foreach(Patient patient in Model)
{
  <li>@Html.ActionLink($"{patient.PatientName}", "Details", new { id = patient.PatientId })</li>
}

<p>@Html.ActionLink("Add New Patient", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>