Desktop/university_registrar-main/Registry/Models/Course.cs
using System.Collections.Generic;

namespace Registry.Models
{
  public class Course
  {
    public Course()
    {
      this.Students = new HashSet<CourseStudent>();
    }
    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public virtual ICollection<CourseStudent> Students { get; set; }
  }
}

Desktop/university_registrar-main/Registry/Models/CourseStudent.cs
namespace Registry.Models
{
  public class CourseStudent
  {
    public int CourseStudentId { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }
    public Student Student { get; set; }
    public Course Course { get; set; }
  }
}

Desktop/university_registrar-main/Registry/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Registry.Models
{
  public class RegistryContextFactory : IDesignTimeDbContextFactory<RegistryContext>
  {

    RegistryContext IDesignTimeDbContextFactory<RegistryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<RegistryContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new RegistryContext(builder.Options);
    }
  }
}

Desktop/university_registrar-main/Registry/Models/RegistryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Registry.Models
{
  public class RegistryContext : DbContext
  {
    public virtual DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<CourseStudent> CourseStudent { get; set; }

    public RegistryContext(DbContextOptions options) : base(options) { }
  }
}

Desktop/university_registrar-main/Registry/Models/Student.cs
using System.Collections.Generic;

namespace Registry.Models
{
  public class Student
  {
    public Student()
    {
      this.Courses = new HashSet<CourseStudent>();
    }

    public int StudentId { get; set; }
    public string StudentName { get; set; }
    public string DOE { get; set; }

    public ICollection<CourseStudent> Courses { get; }

  }
}

Desktop/university_registrar-main/Registry/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Registry.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Registry.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistryContext _db;
    public CoursesController(RegistryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCourse = _db.Courses
        .Include(course => course.Students)
        .ThenInclude(join => join.Student)
        .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Desktop/university_registrar-main/Registry/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Registry.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Desktop/university_registrar-main/Registry/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Registry.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registry.Controllers
{
  public class StudentsController : Controller
  {
    private readonly RegistryContext _db;

    public StudentsController(RegistryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Students.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student, int CourseId)
    {
      _db.Students.Add(student);
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisStudent = _db.Students
          .Include(student => student.Courses)
          .ThenInclude(join => join.Course)
          .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    public ActionResult Edit(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult Edit(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId}); 
      }
      _db.Entry(student).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCourse(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult AddCourse(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCourse(int joinId)
    {
      var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
      _db.CourseStudent.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Desktop/university_registrar-main/Registry/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Course

<h4>Add a Course</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.CourseName)
    @Html.TextBoxFor(model => model.CourseName)
    <input type="submit" value="Add new course" />
}
<p>@Html.ActionLink("show all courses", "Index")</p>

Desktop/university_registrar-main/Registry/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Course

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.CourseName): @Html.DisplayFor(model => model.CourseName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Courses", "Index")

Desktop/university_registrar-main/Registry/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Course;

<h2>Course Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.CourseName): @Html.DisplayFor(model => model.CourseName)</h3>

@if(@Model.Students.Count == 0)
{
  <p>This course has no students assigned to it</p>
}
else
{
  <h4>Students in this course:</h4>
  <ul>
    @foreach(var join in Model.Students)
    {
      <li>@join.Student.StudentName</li>
    }
  </ul>
}

<p>@Html.ActionLink("Back to Courses", "Index")</p>
<p>@Html.ActionLink("Edit Course", "Edit", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>

Desktop/university_registrar-main/Registry/Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Course

<h2>Edit</h2>

<h4>Edit this Course: @Html.DisplayFor(model => model.CourseName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)

  @Html.LabelFor(model => model.CourseName)
  @Html.EditorFor(model => model.CourseName)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Courses", "Index")</p>

Desktop/university_registrar-main/Registry/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registry.Models;
@model List<Registry.Models.Course>;

<h1>Courses</h1>

@if (@Model.Count == 0)
{
  <h3>No Courses are active yet!</h3>
}

@foreach (Course course in Model)
{
  <li>@Html.ActionLink($"{course.CourseName}", "Details", new { id = course.CourseId })</li>
}

<p>@Html.ActionLink("Add new course", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Desktop/university_registrar-main/Registry/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the University Registry!</h1>
<p>@Html.ActionLink("See all Students", "Index", "Students")</p> 
<p>@Html.ActionLink("See all Courses", "Index", "Courses")</p>

Desktop/university_registrar-main/Registry/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>University Registry</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

Desktop/university_registrar-main/Registry/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Student

<h2>Add a Course</h2>

<h2>Add a course for: @Html.DisplayFor(model => model.StudentName)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.Label("Select course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to students", "Index")</p>

Desktop/university_registrar-main/Registry/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Student

<h4>Enroll a new student</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.StudentName)
    @Html.TextBoxFor(model => model.StudentName)

    @Html.Label("Select Course")
    @Html.DropDownList("CourseId")

    @Html.Label("Date of Enrollment")
    @Html.TextBoxFor(model => model.DOE, new { @type = "date"})

    <input type="submit" value="Enroll new student" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all students", "Index")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

Desktop/university_registrar-main/Registry/Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Student

<h2>Are you sure you want to delete this student?</h2>

@Html.DisplayNameFor(model => model.StudentName): @Html.DisplayFor(model => model.StudentName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back To Students", "Index")

Desktop/university_registrar-main/Registry/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Student

<h2>Student Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.StudentName): @Html.DisplayFor(model => model.StudentName)</h3>
<h3>@Html.DisplayNameFor(model => model.DOE): @Html.DisplayFor(model => model.DOE)</h3>
  @if(@Model.Courses.Count == 0)
  {
  <p>This student is not enrolled for any courses</p>
  }
  else
  {
    <h4>Courses the student is enrolled in:</h4>
    <ul>
    @foreach(var join in Model.Courses)
    {
      <li>@join.Course.CourseName</li>
    }
    </ul>
  }

  <ul>
  @foreach(var join in Model.Courses)
  {
    <li>@join.Course.CourseName</li>
    @using (Html.BeginForm("DeleteCourse", "Students"))
    {
      @Html.Hidden("joinId", @join.CourseStudentId)
      <input type="submit" value="Delete"/>
    } 
  }
  </ul>

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Student", "Edit", new { id = Model.StudentId})</p>
<p>@Html.ActionLink("Delete Student", "Delete", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Add a Course", "AddCourse", new { id = Model.StudentId })</p>

Desktop/university_registrar-main/Registry/Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Registry.Models.Student

<h2>Edit</h2>

<h4>Edit: @Html.DisplayFor(model => model.StudentName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)

  @Html.LabelFor(model => model.StudentName)
  @Html.EditorFor(model => model.StudentName)

  @Html.Label("Select a course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Save" />
  
}

<p>@Html.ActionLink("Back to Students", "Index")</p>

Desktop/university_registrar-main/Registry/Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registry.Models;
@model List<Registry.Models.Student>;

<h1>Enrolled Students:</h1>

@if (@Model.Count == 0)
{
  <h2>No students have been enrolled yet...</h2>
}

@foreach(Student student in Model)
{
  <li>@Html.ActionLink($"{student.StudentName}", "Details", new { id = student.StudentId })</li>
}

<p>@Html.ActionLink("Add New Student", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>