Desktop/doctors-office-main/Office/Models/Doctor.cs
using System.Collections.Generic;
using System;

namespace Office.Models
{
  public class Doctor
  {
    public Doctor()
    {
      // this.Patients = new HashSet<DoctorPatient>();
      this.Patients = new HashSet<DoctorPatientSpecialty>();
      this.Specialties = new HashSet<DoctorPatientSpecialty>();
    }
    public int DoctorId { get; set; }
    public string DoctorName { get; set; }
    public string DoctorSpecialty { get; set; }

    // public virtual ICollection<DoctorPatient> Patients { get; set; }
    public ICollection<DoctorPatientSpecialty> Patients { get; set; }
    public ICollection<DoctorPatientSpecialty> Specialties { get; set; }
  }
}

Desktop/doctors-office-main/Office/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Mvc;
using Office.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Office.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly OfficeContext _db;
    public DoctorsController(OfficeContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Doctor> model = _db.Doctors.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Doctor doctor)
    {
      _db.Doctors.Add(doctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
      .Include(doctor => doctor.Patients)
      .ThenInclude(join => join.Patient)
      .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }
    public ActionResult Edit(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }
    [HttpPost]
    public ActionResult Edit(Doctor doctor)
    {
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      _db.Doctors.Remove(thisDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Desktop/doctors-office-main/Office/Views/Doctors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Doctor

<h4>Add a Doctor</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.DoctorName)
    @Html.TextBoxFor(model => model.DoctorName)

    @Html.LabelFor(model => model.DoctorSpecialty)
    @Html.TextBoxFor(model => model.DoctorSpecialty)

    <input type="submit" value="Add New Doctor" class="btn btn-default" />
}
<p>@Html.ActionLink("Show All Doctors", "Index")</p>

Desktop/doctors-office-main/Office/Views/Doctors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Doctor

<h2>Are you sure you want to delete this Doctor?</h2>

@Html.DisplayNameFor(model => model.DoctorName): @Html.DisplayFor(model => model.DoctorName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-default" />
}
@Html.ActionLink("Back to Doctors", "Index")

Desktop/doctors-office-main/Office/Views/Doctors/Details.cshtml
@{
  Layout = "_Layout";
}
@model Office.Models.Doctor;

<h2>Doctor Overview</h2>
<hr />
<h3>Doctor: @Html.DisplayFor(model => model.DoctorName)</h3>
<h3>Specialty: @Html.DisplayFor(model => model.DoctorSpecialty)</h3>

@if(@Model.Patients.Count == 0)
{
  <p>This Doctor is currently not assigned to any patients.</p>
}
else
{
  <h4><u>Assigned Patients; Doctor @Html.DisplayFor(model => model.DoctorName)</u></h4>
  <ul>
    @foreach(var join in Model.Patients)
    {
      <li>@join.Patient.PatientName</li>
    }
  </ul>  
}
<p>@Html.ActionLink("Edit Doctor Information", "Edit", new { id = Model.DoctorId })

Desktop/doctors-office-main/Office/Views/Doctors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Office.Models.Doctor

<h2>Edit</h2>

<h4>Edit this Doctor: @Html.DisplayFor(model => model.DoctorName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DoctorId)

  @Html.LabelFor(model => model.DoctorName)
  @Html.EditorFor(model => model.DoctorName)

  <input type="submit" value="Save" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to Doctors", "Index")</p>

Desktop/doctors-office-main/Office/Views/Doctors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Office.Models;
@model List<Office.Models.Doctor>;

<h1>Doctors | Specialties</h1>
<hr />
@if (@Model.Count == 0)
{
<h3>There are no Doctors hired.</h3>
}

@foreach (Doctor doctor in Model)
{
  <li>@Html.ActionLink($"{doctor.DoctorName}", "Details", new { id = doctor.DoctorId })</li>
  //<li>@Html.DisplayFor(model => model.DoctorSpecialty)</li>
  @using (Html.BeginForm("Delete", "Doctors", FormMethod.Get))
  {
    @Html.Hidden("id", @doctor.DoctorId)
    <input type="submit" value="Remove Doctor" class="btn btn-default"/>
  }
}
<br><p>@Html.ActionLink("Add a new Hire", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>